### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by JohanEngelen** [JinShil/stm32f42_discovery_demo#3]
The links in the readme to code fragments like the "Compile-time enforcement of register/bitfield mutability" are to master branch code, instead of to a fixed point in git history (git commit hash). Because of code changes in the meanwhile, the line numbers are no longer correct.
It would help if the links are to a specific commit hash, such as this one:
https://github.com/JinShil/stm32f42_discovery_demo/blob/c324bbf861cf258a819478481521528fca88dcb3/build.d#L18

**Comment by JinShil** [comment]
Fixed.  Thanks!
